// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-PaD8N6G6uU-LZfaT__rMUeUmAzkOMfA',
    appId: '1:49200158446:web:1f58c62e952f4009f145ff',
    messagingSenderId: '49200158446',
    projectId: 'tikutoku-jh124',
    authDomain: 'tikutoku-jh124.firebaseapp.com',
    storageBucket: 'tikutoku-jh124.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX0el4Q4ZmxhzEHnvO3_B3SVLk3RzQg2A',
    appId: '1:49200158446:android:88532f3c23957e07f145ff',
    messagingSenderId: '49200158446',
    projectId: 'tikutoku-jh124',
    storageBucket: 'tikutoku-jh124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFaAX9VNp8NW1ou6a8bl_53iRWLnLs0k',
    appId: '1:49200158446:ios:f506e1531d7ed293f145ff',
    messagingSenderId: '49200158446',
    projectId: 'tikutoku-jh124',
    storageBucket: 'tikutoku-jh124.appspot.com',
    iosClientId: '49200158446-17c99qqdibesgii0and7iv0h63vdi7j4.apps.googleusercontent.com',
    iosBundleId: 'com.clonecode.tiktok',
  );
}
